returns/urls.py
from django.urls import path

from . import views
from .views import TransactionListView, TransactionDetailView

urlpatterns = [
    path('', views.index, name='index'),
    path('get_orders/', views.get_orders, name='get_orders'),
    path('new_transaction/', views.insert_new_transaction, name='new_transaction'),
    path('transactions/', TransactionListView.as_view(), name='transaction_list'),
    path('transactions/<int:pk>', TransactionDetailView.as_view(), name='transaction_detail'),
    path('transactions/<int:pk>/edit', views.update_transaction, name='transaction_edit'),
]

wecarecms/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('returns/', include('returns.urls')),
    path('admin/', admin.site.urls),
]

returns/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
class Order(models.Model):
    order_id  = models.IntegerField(default=0)
    customer_name = models.CharField(max_length=250)
    order_date = models.DateTimeField('date Order was received')
    invoice_date = models.DateTimeField('date Order was invoiced')
    payment = models.CharField(max_length=250, null=True)
    transport = models.CharField(max_length=250, null=True)
    total_amount = models.FloatField(null=True, blank=True, default=None)
    delivery_cost = models.FloatField(null=True, blank=True, default=None)
    transport_cost = models.FloatField(null=True, blank=True, default=None)
    status = models.IntegerField(default=0)
    fincode = models.CharField(max_length=20, null=True)
    series = models.CharField(max_length=10, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.order_id

    def was_received_recently(self):
        return self.invoice_date >= timezone.now() - datetime.timedelta(days=20)


class Transaction(models.Model):
    CHANGE_ORDER = 'CH'
    CANCEL_ORDER = 'CA'
    EM_ORDER = 'EM'
    XX_ORDER = 'XX'
    NO_SEND = 'NO'
    RETURN_PROD = 'RP'

    TRANSACTION_TYPE_CHOICES = [  
        (CHANGE_ORDER, 'Μεταβολή Παραγγελίας'), 
        (CANCEL_ORDER, 'Ακύρωση'),
        (EM_ORDER, 'EM'),
        (RETURN_PROD, 'Επιστροφή Προϊόντος'),
        (XX_ORDER, 'Χωρίς Χρέωση'),
        (NO_SEND, 'Xωρίς αποστολή'), 
    ]

    NEW_ORDER_STATUS =  [
        ('PE', 'Pending'),
        ('OK', 'Μπήκε Πληρωμένη'), 
        ('CA', 'Canceled'), 
     ]

    FAULT_OF =  [
        ('WA', 'Αποθήκη'),        
        ('TC', 'Τηλεφωνικό Κέντρο'), 
        ('AC', 'ACS'),
        ('GE', 'ΓΕΝΙΚΗ ΤΑΧΥΔΡΟΜΙΚΗ'),
        ('ET', 'Εταιρεία Παραγωγός'), 
        ('OT', 'Άλλο'), 
     ]

    FAULT_TYPE =  [
        ('EL', 'Δεν έχουμε το προϊόν'),
        ('ES', 'Λάθος στοκ στο Site'), 
        ('SP', 'Σπασμένο Δέμα'), 
        ('LA', 'Λαθος προϊόν'),
        ('KA', 'Καθυστερημένη παράδοση'),        
        ('OT', 'Άλλο'), 
     ]

    original_order  = models.CharField(max_length=10, default='0')
    new_order  =  models.CharField(max_length=10, null= True, blank =True)
    trans_type = models.CharField(max_length=2, choices=TRANSACTION_TYPE_CHOICES, default=CHANGE_ORDER,)    
    customer_name = models.CharField(max_length=250, default='No Name')
    original_order_payment = models.CharField(max_length=250, null=True, blank=True)
    
    description = models.TextField(null=True, blank = True)
    status = models.CharField(max_length=2, choices=NEW_ORDER_STATUS, default='PE')
    fault_of = models.CharField(max_length=2, choices=FAULT_OF, null=True, blank=True)
    fault_type = models.CharField(max_length=2, choices=FAULT_TYPE, null=True, blank=True)
    original_amount = models.FloatField(null=True, blank=True, default=0)   
    new_amount = models.FloatField(null=True, blank=True, default=0)
    
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True,null=True)

    def is_pending_transaction(self):
        return self.status == 'PE'
    
    def save_model(self, request, obj, form, change):
        obj.author = request.user
        super().save_model(request, obj, form, change)
    
    def get_absolute_url(self):
        return reverse('transaction_detail', kwargs={'pk': self.pk})


class MoneyTransfer(models.Model):  

    TRANSFER_ACCOUNT =  [
        ('PE', 'ΠΕΙΡΑΙΩΣ'),
        ('EU', 'EUROBANK'), 
        ('AL', 'ALPHABANK'),  
        ('NB', 'ΕΘΝΙΚΗ'),  
        ('PI', 'ΠΙΣΤΩΤΙΚΗ'), 
        ('PI', 'PAYPAL'),  
        ('ME', 'ΜΕΤΡΗΤΑ'),
    ]

    TRANSFER_STATUS =  [
        ('PE', 'Pending'),
        ('OK', 'Completed'), 
        ('CA', 'Canceled'), 
     ]

     

    transaction  = models.ForeignKey(Transaction, on_delete=models.CASCADE, related_name="transaction_order",)
    transfer_account = models.CharField(max_length=2, choices=TRANSFER_ACCOUNT)
    iban = models.CharField(max_length=50, null=True, blank=True)
    bank_name = models.CharField(max_length=250, null=True, blank=True)
    ammount = models.FloatField(default=0)
    comments = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=2, choices=TRANSFER_STATUS)
    transaction_details = models.TextField( null=True, blank=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.transaction

    def is_pending_transfer(self):
        return self.status =='PE'

returns/forms.py
from django import forms
from django.forms import ModelForm
from returns.models import Transaction
from django.contrib.auth.models import User

class Get_orders_form(forms.Form):
    original_order_id = forms.CharField(label='Αρχική Παραγγελία', max_length=10)
    new_order_id = forms.CharField(label='Νέα Παραγγελία', max_length=10)

class TransactionForm(ModelForm):
    class Meta:
        model = Transaction
        fields = ['original_order', 'new_order', 'trans_type', 'status', 'customer_name','original_order_payment',
        'original_amount', 'new_amount','description', 'fault_of', 'fault_type']


class MoneyTransfer(ModelForm):
    class Meta:
        model = MoneyTransfer
        fields = ['transaction', 'transfer_account', 'iban', 'bank_name', 'ammount','comments',
        'status', 'transaction_details']
    
    

returns/views.py
from django.http import HttpResponse, HttpResponseRedirect

from django.template import loader
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from .apps import ReturnsLibs
from .models import Transaction
from .forms import Get_orders_form, TransactionForm


class TransactionListView(ListView):
    model = Transaction
    template_name = 'transaction_list.html'
    ordering = ['-id']
class TransactionDetailView(DetailView):
    model = Transaction
    template_name = 'transaction_detail.html'
  
def index(request):    
   
    return HttpResponse(ReturnsLibs.sw.get_order_data('501100'))

def get_order_data(order_id):
    try:
        order_data = ReturnsLibs.sw.get_order_data(order_id)
        if order_data['success']:
            if order_data['totalcount']>0:
                return order_data
            else:
                return None
    except Exception as ex:
        return None


def get_orders(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = Get_orders_form(request.POST)
        # check whether it's valid:
        if form.is_valid():           
            
            request.session["orders_form"] = request.POST.dict()  #save the form as a dict in request.sessions                 
            return redirect('/returns/new_transaction/')     
    # if a GET (or any other method) we'll create a blank form
    else:
        print('request get')
        form = Get_orders_form()
    return render(request, 'get_orders.html', {'form': form})


def insert_new_transaction(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = TransactionForm(request.POST)
        # check whether it's valid:
        print(request.POST)
        if form.is_valid():                           
            # Save a new Article object from the form's data.
            new_transaction = form.save()
            print(new_transaction)
            #return render(request, 'insert.html', {'form': form, 'context': context})
            return redirect('/returns/transactions/{0}'.format(new_transaction.pk))
    # if a GET (or any other method) we'll create a blank form
    else:
        form_data = request.session.pop('orders_form', {})        
        context = {}       
        original_order_id = form_data.get("original_order_id")
        new_order_id = form_data.get('new_order_id')
        original_order_data = get_order_data(original_order_id)
        new_order_data = get_order_data(new_order_id)

        if original_order_data!=None:
            context['original_order_data'] = original_order_data
            if new_order_data!=None:
                context['new_order_data'] = new_order_data     
                form = TransactionForm(
                    initial={
                        'original_order': original_order_id,
                        'new_order': new_order_id,
                        'customer_name': original_order_data['rows'][0]['NAME'],
                        'original_order_payment': original_order_data['rows'][0]['PAYMENT'],
                        'original_amount':original_order_data['rows'][0]['SUMAMNT'],
                        'new_amount':new_order_data['rows'][0]['SUMAMNT']
                        })  
            else:
                form = TransactionForm(
                    initial={
                        'original_order': original_order_id,                        
                        'customer_name': original_order_data['rows'][0]['NAME'],
                        'original_order_payment': original_order_data['rows'][0]['PAYMENT'],
                        'original_amount':original_order_data['rows'][0]['SUMAMNT'],                        
                        })  
        else:
            form = TransactionForm()
        

    return render(request, 'insert.html', {'form': form, 'context':context})

def update_transaction(request, pk):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = TransactionForm(request.POST)
        # check whether it's valid:
        if form.is_valid():                           
            # Save a new Article object from the form's data.
            trans = form.save()
            return redirect('/returns/transactions/')
    else:
        transaction = Transaction.objects.get(pk=pk)
        form = TransactionForm(instance=transaction)

    return render(request, 'insert.html', {'form': form})        

returns/templates/base.html
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </head>
    <title>
        Wecare CMS
    </title>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

returns/templates/get_orders.html
<html>
    <header>

    </header>
    <body>
       
        <div class="container">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="Submit" name="frm_get_orders">
                </form>
         </div>

         <div class="container">
             {% if context.original_order_data %}
                 <div>
                     <a href="../new_transaction/">Εισαγωγη</a>
                 </div>
                {{context.original_order_data}}
             {% endif %}
         </div>
         <div class="container">
             {% if context.new_order_data %}
                {{context.new_order_data}}
             {% endif %}
         </div>
         

    </body>
</html>

returns/templates/insert.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <table class="table">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="Submit" name="frm_insert">
            </form>
        </table>
        </div>

{% endblock %}      
        

returns/templates/money_transfer_edit.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <table class="table">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="Submit" name="frm_insert">
            </form>
        </table>
        </div>

{% endblock %}      
        

returns/templates/transaction_detail.html
{% extends "base.html" %}
{% block content %}
<h1>{{ object.customer_name }}</h1>
<h1>{{ object.get_status_display }}</h1>
<p>Πληρωμή Αρχικής παραγγελίας: {{ object.original_order_payment }}</p>
<p>Περιγραφή: {{ object.description }}</p>
<p>Created: {{ object.created_at|date }}</p>
<p>Updated: {{ object.updated_at|date }}</p>

<a class="btn btn-primary" href="{{ object.pk }}/edit" role="button">ΑΛΛΑΓΗ</a>
{% endblock %}      
        

returns/templates/transaction_list.html
{% extends "base.html" %}

{% block content %}
    <h2>Transactions</h2>
    <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Original Order</th>
                <th scope="col">Cloned Order</th>
                <th scope="col">Transaction Type</th>
                <th scope="col">Status</th>
                <th scope="col">Payment</th>
                <th scope="col">Created at</th>
                <th scope="col">Updated at</th>
                <th scope="col">User</th>
              </tr>
            </thead>
            <tbody>
                {% for transaction in object_list %}

                    <tr>
                        <th scope="row">{{ transaction.id }}</th>
                        <td><a href="{{ transaction.pk }}">{{ transaction.customer_name }}</a></td>
                        <td>{{ transaction.original_order }}</td>
                        <td>{{ transaction.new_order }}</td>
                        <td>{{ transaction.get_trans_type_display }}</td>
                        <td>{{ transaction.get_status_display }}</td>
                        <td>{{ transaction.original_order_payment }}</td>
                        <td>{{ transaction.created_at|date }}</td>  
                        <td>{{ transaction.updated_at|date }}</td>     
                        <td>{{ transaction.author }}</td>                        
                    </tr>
                
                {% endfor %}             
            </tbody>
          </table>
   
{% endblock %}